import { UserProfile, Match, Conversation, Message } from "@/types";

export const currentUser: UserProfile = {
  id: "user-1",
  name: "Alex Chen",
  avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Alex",
  age: 28,
  location: "San Francisco, CA",
  nativeLanguage: "English",
  learningLanguages: ["Mandarin", "Spanish"],
  bio: "Language enthusiast, coffee lover, and tech geek. Looking to practice Mandarin and Spanish with native speakers.",
  interests: ["Travel", "Photography", "Cooking", "Tech"],
  responseRate: 0.95,
  lastSeen: new Date(),
  verified: true,
  premium: true,
};

export const suggestedMatches: Match[] = [
  {
    id: "match-1",
    user: {
      id: "user-2",
      name: "María García",
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maria",
      age: 26,
      location: "Madrid, Spain",
      nativeLanguage: "Spanish",
      learningLanguages: ["English", "Italian"],
      bio: "Native Spanish speaker eager to improve my English. Love traveling and meeting new people.",
      interests: ["Travel", "Cooking", "Art", "Music"],
      responseRate: 0.92,
      lastSeen: new Date(Date.now() - 3600000),
      verified: true,
      premium: false,
    },
    compatibility: 0.94,
    commonInterests: ["Travel", "Cooking"],
    matchedAt: new Date(Date.now() - 86400000),
    status: "new",
  },
  {
    id: "match-2",
    user: {
      id: "user-3",
      name: "Wei Lin",
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Wei",
      age: 25,
      location: "Shanghai, China",
      nativeLanguage: "Mandarin",
      learningLanguages: ["English", "Japanese"],
      bio: "Software engineer from Shanghai. Native Mandarin speaker interested in language exchange.",
      interests: ["Tech", "Photography", "Gaming", "Hiking"],
      responseRate: 0.88,
      lastSeen: new Date(Date.now() - 1800000),
      verified: true,
      premium: true,
    },
    compatibility: 0.91,
    commonInterests: ["Tech", "Photography"],
    matchedAt: new Date(Date.now() - 172800000),
    status: "connected",
  },
  {
    id: "match-3",
    user: {
      id: "user-4",
      name: "Luis Morales",
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Luis",
      age: 29,
      location: "Mexico City, Mexico",
      nativeLanguage: "Spanish",
      learningLanguages: ["English", "Portuguese"],
      bio: "Architect and Spanish teacher. Passionate about helping others learn Spanish.",
      interests: ["Architecture", "Design", "Cooking", "Travel"],
      responseRate: 0.96,
      lastSeen: new Date(Date.now() - 7200000),
      verified: true,
      premium: false,
    },
    compatibility: 0.89,
    commonInterests: ["Cooking", "Travel"],
    matchedAt: new Date(Date.now() - 259200000),
    status: "chatting",
  },
  {
    id: "match-4",
    user: {
      id: "user-5",
      name: "Sophie Dubois",
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sophie",
      age: 27,
      location: "Paris, France",
      nativeLanguage: "French",
      learningLanguages: ["English", "Spanish"],
      bio: "Artist and language lover. Always excited to meet people from different cultures.",
      interests: ["Art", "Photography", "Museums", "Music"],
      responseRate: 0.91,
      lastSeen: new Date(Date.now() - 3600000),
      verified: true,
      premium: true,
    },
    compatibility: 0.87,
    commonInterests: ["Photography", "Art"],
    matchedAt: new Date(Date.now() - 345600000),
    status: "new",
  },
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    participantId: "user-3",
    participantName: "Wei Lin",
    participantAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Wei",
    lastMessage: {
      id: "msg-5",
      conversationId: "conv-1",
      senderId: "user-3",
      senderName: "Wei Lin",
      type: "audio",
      content: "Audio message",
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      audioDuration: 5,
      timestamp: new Date(Date.now() - 1800000),
      read: true,
    },
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 1800000),
    status: "active",
  },
  {
    id: "conv-2",
    participantId: "user-2",
    participantName: "María García",
    participantAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maria",
    lastMessage: {
      id: "msg-4",
      conversationId: "conv-2",
      senderId: "user-1",
      senderName: "You",
      type: "text",
      content: "That sounds amazing! Let's chat more about it.",
      timestamp: new Date(Date.now() - 3600000),
      read: true,
    },
    unreadCount: 1,
    updatedAt: new Date(Date.now() - 3600000),
    status: "active",
  },
];

export const messages: Message[] = [
  {
    id: "msg-1",
    conversationId: "conv-1",
    senderId: "user-1",
    senderName: "You",
    type: "text",
    content: "Hi Wei! How are you doing today?",
    timestamp: new Date(Date.now() - 7200000),
    read: true,
  },
  {
    id: "msg-2",
    conversationId: "conv-1",
    senderId: "user-3",
    senderName: "Wei Lin",
    type: "text",
    content: "I'm doing great! Just finished a project at work. How about you?",
    timestamp: new Date(Date.now() - 7020000),
    read: true,
  },
  {
    id: "msg-3",
    conversationId: "conv-1",
    senderId: "user-1",
    senderName: "You",
    type: "text",
    content: "That's awesome! I'm working on learning more Mandarin phrases.",
    timestamp: new Date(Date.now() - 6840000),
    read: true,
  },
  {
    id: "msg-4",
    conversationId: "conv-1",
    senderId: "user-3",
    senderName: "Wei Lin",
    type: "text",
    content: "I can help you! Here are some useful phrases for you.",
    timestamp: new Date(Date.now() - 3600000),
    read: true,
  },
  {
    id: "msg-5",
    conversationId: "conv-1",
    senderId: "user-3",
    senderName: "Wei Lin",
    type: "audio",
    content: "Audio message",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    audioDuration: 5,
    timestamp: new Date(Date.now() - 1800000),
    read: true,
  },
];

export const languages = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Portuguese",
  "Italian",
  "Russian",
  "Arabic",
  "Hindi",
];

export const interests = [
  "Travel",
  "Photography",
  "Cooking",
  "Tech",
  "Art",
  "Music",
  "Gaming",
  "Hiking",
  "Reading",
  "Sports",
  "Movies",
  "Design",
];
